package com.abk.brodue

data class Country(val name: String, val code: String, val iso: String)

object CountryCodes {
    val list = listOf(
        Country("Afghanistan", "+93", "AF"),
        Country("Albania", "+355", "AL"),
        Country("Algeria", "+213", "DZ"),
        Country("Andorra", "+376", "AD"),
        Country("Angola", "+244", "AO"),
        Country("Antigua and Barbuda", "+1268", "AG"),
        Country("Argentina", "+54", "AR"),
        Country("Armenia", "+374", "AM"),
        Country("Australia", "+61", "AU"),
        Country("Austria", "+43", "AT"),
        Country("Azerbaijan", "+994", "AZ"),
        Country("Bahamas", "+1242", "BS"),
        Country("Bahrain", "+973", "BH"),
        Country("Bangladesh", "+880", "BD"),
        Country("Barbados", "+1246", "BB"),
        Country("Belarus", "+375", "BY"),
        Country("Belgium", "+32", "BE"),
        Country("Belize", "+501", "BZ"),
        Country("Benin", "+229", "BJ"),
        Country("Bhutan", "+975", "BT"),
        Country("Bolivia", "+591", "BO"),
        Country("Bosnia and Herzegovina", "+387", "BA"),
        Country("Botswana", "+267", "BW"),
        Country("Brazil", "+55", "BR"),
        Country("Brunei", "+673", "BN"),
        Country("Bulgaria", "+359", "BG"),
        Country("Burkina Faso", "+226", "BF"),
        Country("Burundi", "+257", "BI"),
        Country("Cambodia", "+855", "KH"),
        Country("Cameroon", "+237", "CM"),
        Country("Canada", "+1", "CA"),
        Country("Cape Verde", "+238", "CV"),
        Country("Central African Republic", "+236", "CF"),
        Country("Chad", "+235", "TD"),
        Country("Chile", "+56", "CL"),
        Country("China", "+86", "CN"),
        Country("Colombia", "+57", "CO"),
        Country("Comoros", "+269", "KM"),
        Country("Congo", "+242", "CG"),
        Country("Congo, Democratic Republic", "+243", "CD"),
        Country("Costa Rica", "+506", "CR"),
        Country("Croatia", "+385", "HR"),
        Country("Cuba", "+53", "CU"),
        Country("Cyprus", "+357", "CY"),
        Country("Czech Republic", "+420", "CZ"),
        Country("Denmark", "+45", "DK"),
        Country("Djibouti", "+253", "DJ"),
        Country("Dominica", "+1767", "DM"),
        Country("Dominican Republic", "+1809", "DO"),
        Country("Ecuador", "+593", "EC"),
        Country("Egypt", "+20", "EG"),
        Country("El Salvador", "+503", "SV"),
        Country("Equatorial Guinea", "+240", "GQ"),
        Country("Eritrea", "+291", "ER"),
        Country("Estonia", "+372", "EE"),
        Country("Eswatini", "+268", "SZ"),
        Country("Ethiopia", "+251", "ET"),
        Country("Fiji", "+679", "FJ"),
        Country("Finland", "+358", "FI"),
        Country("France", "+33", "FR"),
        Country("Gabon", "+241", "GA"),
        Country("Gambia", "+220", "GM"),
        Country("Georgia", "+995", "GE"),
        Country("Germany", "+49", "DE"),
        Country("Ghana", "+233", "GH"),
        Country("Greece", "+30", "GR"),
        Country("Grenada", "+1473", "GD"),
        Country("Guatemala", "+502", "GT"),
        Country("Guinea", "+224", "GN"),
        Country("Guinea-Bissau", "+245", "GW"),
        Country("Guyana", "+592", "GY"),
        Country("Haiti", "+509", "HT"),
        Country("Honduras", "+504", "HN"),
        Country("Hungary", "+36", "HU"),
        Country("Iceland", "+354", "IS"),
        Country("India", "+91", "IN"),
        Country("Indonesia", "+62", "ID"),
        Country("Iran", "+98", "IR"),
        Country("Iraq", "+964", "IQ"),
        Country("Ireland", "+353", "IE"),
        Country("Israel", "+972", "IL"),
        Country("Italy", "+39", "IT"),
        Country("Jamaica", "+1876", "JM"),
        Country("Japan", "+81", "JP"),
        Country("Jordan", "+962", "JO"),
        Country("Kazakhstan", "+7", "KZ"),
        Country("Kenya", "+254", "KE"),
        Country("Kiribati", "+686", "KI"),
        Country("Korea, North", "+850", "KP"),
        Country("Korea, South", "+82", "KR"),
        Country("Kosovo", "+383", "XK"),
        Country("Kuwait", "+965", "KW"),
        Country("Kyrgyzstan", "+996", "KG"),
        Country("Laos", "+856", "LA"),
        Country("Latvia", "+371", "LV"),
        Country("Lebanon", "+961", "LB"),
        Country("Lesotho", "+266", "LS"),
        Country("Liberia", "+231", "LR"),
        Country("Libya", "+218", "LY"),
        Country("Liechtenstein", "+423", "LI"),
        Country("Lithuania", "+370", "LT"),
        Country("Luxembourg", "+352", "LU"),
        Country("Madagascar", "+261", "MG"),
        Country("Malawi", "+265", "MW"),
        Country("Malaysia", "+60", "MY"),
        Country("Maldives", "+960", "MV"),
        Country("Mali", "+223", "ML"),
        Country("Malta", "+356", "MT"),
        Country("Marshall Islands", "+692", "MH"),
        Country("Mauritania", "+222", "MR"),
        Country("Mauritius", "+230", "MU"),
        Country("Mexico", "+52", "MX"),
        Country("Micronesia", "+691", "FM"),
        Country("Moldova", "+373", "MD"),
        Country("Monaco", "+377", "MC"),
        Country("Mongolia", "+976", "MN"),
        Country("Montenegro", "+382", "ME"),
        Country("Morocco", "+212", "MA"),
        Country("Mozambique", "+258", "MZ"),
        Country("Myanmar", "+95", "MM"),
        Country("Namibia", "+264", "NA"),
        Country("Nauru", "+674", "NR"),
        Country("Nepal", "+977", "NP"),
        Country("Netherlands", "+31", "NL"),
        Country("New Zealand", "+64", "NZ"),
        Country("Nicaragua", "+505", "NI"),
        Country("Niger", "+227", "NE"),
        Country("Nigeria", "+234", "NG"),
        Country("North Macedonia", "+389", "MK"),
        Country("Norway", "+47", "NO"),
        Country("Oman", "+968", "OM"),
        Country("Pakistan", "+92", "PK"),
        Country("Palau", "+680", "PW"),
        Country("Palestine", "+970", "PS"),
        Country("Panama", "+507", "PA"),
        Country("Papua New Guinea", "+675", "PG"),
        Country("Paraguay", "+595", "PY"),
        Country("Peru", "+51", "PE"),
        Country("Philippines", "+63", "PH"),
        Country("Poland", "+48", "PL"),
        Country("Portugal", "+351", "PT"),
        Country("Qatar", "+974", "QA"),
        Country("Romania", "+40", "RO"),
        Country("Russia", "+7", "RU"),
        Country("Rwanda", "+250", "RW"),
        Country("Saint Kitts and Nevis", "+1869", "KN"),
        Country("Saint Lucia", "+1758", "LC"),
        Country("Saint Vincent and the Grenadines", "+1784", "VC"),
        Country("Samoa", "+685", "WS"),
        Country("San Marino", "+378", "SM"),
        Country("Sao Tome and Principe", "+239", "ST"),
        Country("Saudi Arabia", "+966", "SA"),
        Country("Senegal", "+221", "SN"),
        Country("Serbia", "+381", "RS"),
        Country("Seychelles", "+248", "SC"),
        Country("Sierra Leone", "+232", "SL"),
        Country("Singapore", "+65", "SG"),
        Country("Slovakia", "+421", "SK"),
        Country("Slovenia", "+386", "SI"),
        Country("Solomon Islands", "+677", "SB"),
        Country("Somalia", "+252", "SO"),
        Country("South Africa", "+27", "ZA"),
        Country("South Sudan", "+211", "SS"),
        Country("Spain", "+34", "ES"),
        Country("Sri Lanka", "+94", "LK"),
        Country("Sudan", "+249", "SD"),
        Country("Suriname", "+597", "SR"),
        Country("Sweden", "+46", "SE"),
        Country("Switzerland", "+41", "CH"),
        Country("Syria", "+963", "SY"),
        Country("Taiwan", "+886", "TW"),
        Country("Tajikistan", "+992", "TJ"),
        Country("Tanzania", "+255", "TZ"),
        Country("Thailand", "+66", "TH"),
        Country("Timor-Leste", "+670", "TL"),
        Country("Togo", "+228", "TG"),
        Country("Tonga", "+676", "TO"),
        Country("Trinidad and Tobago", "+1868", "TT"),
        Country("Tunisia", "+216", "TN"),
        Country("Turkey", "+90", "TR"),
        Country("Turkmenistan", "+993", "TM"),
        Country("Tuvalu", "+688", "TV"),
        Country("Uganda", "+256", "UG"),
        Country("Ukraine", "+380", "UA"),
        Country("United Arab Emirates", "+971", "AE"),
        Country("United Kingdom", "+44", "GB"),
        Country("United States", "+1", "US"),
        Country("Uruguay", "+598", "UY"),
        Country("Uzbekistan", "+998", "UZ"),
        Country("Vanuatu", "+678", "VU"),
        Country("Vatican City", "+379", "VA"),
        Country("Venezuela", "+58", "VE"),
        Country("Vietnam", "+84", "VN"),
        Country("Yemen", "+967", "YE"),
        Country("Zambia", "+260", "ZM"),
        Country("Zimbabwe", "+263", "ZW")
    )

    fun findByCode(code: String): Country? = list.find { it.code == code }
    fun default(): Country = list.find { it.code == "+91" } ?: list[0]
}
